name: Automated API tests using Postman CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST  https://api.github.com/repos/ezra-ai/Playwright-TS/dispatches \
           -H "Authorization: Bearer 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" \
           -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "run-tests"}' \
 
