image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Run automated API tests using Postman CLI
        script:
          # Install Postman CLI
          - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          # Login using your API Key
          - postman login --with-api-key $POSTMAN_API_KEY
          # Run your collection using Postman CLI
          - postman collection run "16603382-15a12b0a-a1a8-4c01-81f1-7c6649c67d26" -e "16603382-613f733f-7ab1-4de3-9520-002c540c677e"
