image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Run automated API tests using Postman CLI
        script:
          # Install Postman CLI
          - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          # Login using your API Key
          - postman login --with-api-key $POSTMAN_API_KEY
          # Run your collection using Postman CLI
          - postman collection run "24559201-a4697822-8cea-4f27-a49b-12573e833348"
